const express = require("express");
const admin = require("firebase-admin"); // make sure firebase-admin is imported

module.exports = (db) => {
  const router = express.Router();
  const classCollection = db.collection("class");

  // Get all classes
  router.get("/", async (req, res) => {
    try {
      const snapshot = await classCollection.get();
      const classes = snapshot.docs.map((doc) => ({
        id: doc.id,
        ...doc.data(),
      }));
      res.json(classes);
    } catch (err) {
      console.error("Error fetching classes:", err);
      res.status(500).json({ error: "Failed to fetch classes" });
    }
  });

  // Create new class with autogenerated ID
  router.post("/", async (req, res) => {
    const { module, time, location, lecturer, course, students } = req.body;

    if (!module || !time || !location || !lecturer || !course) {
      return res.status(400).json({ error: "Missing required class fields" });
    }

    try {
      const [hour, minute] = time.split(":").map(Number);

      const now = new Date();
      const classDateTime = new Date(
        now.getFullYear(),
        now.getMonth(),
        now.getDate(),
        hour,
        minute,
        0,
        0
      );

      const timestamp = admin.firestore.Timestamp.fromDate(classDateTime);

      const newClassData = {
        module,
        time: timestamp,
        location,
        lecturer,
        course,
        students: students || [],
      };

      const docRef = await classCollection.add(newClassData);

      res.status(201).json({
        message: "Class created successfully",
        id: docRef.id,
      });
    } catch (err) {
      console.error("Error creating class:", err);
      res.status(500).json({ error: "Server error" });
    }
  });

  return router;
};
